fix error C2143: syntax error: missing ';' before 'namespace' fix error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
These errors resulted from the compiler going ape due to the undefined LIBASSERT_BEGIN_NAMESPACE macro usage.